name: BuildUbuntu

on:
  [push, pull_request]

jobs:
  ubuntu_build_meshlab:
    name: Build PyMeshLab (Ubuntu)
    runs-on: ubuntu-16.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: checkout sub-submodule vcg
      run: |
        cd meshlab
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Install dependencies
      run: |
       sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libglew-dev libeigen3-dev libgmp-dev
       sudo apt-get install -y libxkbcommon-x11-0 patchelf python3-dev
    - name: Build MeshLab
      run: |
        sh install/linux/build_meshlab.sh
    - name: Build PyMeshLab
      run: |
        sh install/linux/build_pymeshlab.sh
    - name: Upload PyMeshLab
      uses: actions/upload-artifact@v1
      with:
        name: PyMeshLab
        path: PyMeshLab/
