name: TestRelease

on:
  [push, pull_request]
  #release:
  #  types: [published, edited]

jobs:
  test_release_pymeshlab:
    name: Test PyMeshLab
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pyversion: [3.5, 3.6, 3.7, 3.8]
    steps:
    - name: Install Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install PyMeshLab
      run: |
        pip install git+https://github.com/cnr-isti-vclab/PyMeshLab
    - name: Run Tests ${{ matrix.pyversion }}
      run: |
        pip install pytest
        pytest -s --pyargs pymeshlab
    
